### ISSUE TITLE
Heritage of arial font?

### ISSUE THREAD

**Issue by whaleygeek** [skpang/Teensy40_ECU_reader#2]
Your licence states MIT and (c) 2020 SKPang - did you develop the arial_100.c font yourself? If not, could you correctly attribute it's original author and the project/github repo you got it from, so that your open source footprint is clean of any licence violations. 

It is usual to attribute third party bundled materials inside the LICENCE file, as a way to safely include them in your project without them being blanked included under your own copyright notice.

**Comment by skpang** [comment]
It is from Google.
https://fonts.google.com/specimen/Roboto
Converted using:
https://lvgl.io/tools/fontconverter
