### ISSUE TITLE
ecu_reader heritage

### ISSUE THREAD

**Issue by whaleygeek** [skpang/Teensy40_ECU_reader#3]
I presume the ecu_reader module is from one of your other projects, as I think I have seen you use this before on your blogs.

it would be helpful to put a comment in the two source files for ecu_reader, linking to your original github repo for these files, so that their heritage can be followed back to where they originated from. This also helps you to defend your copyright assertion in the future, if it is ever queried.

**Comment by skpang** [comment]
Added in readme to the original ECU reader project.
